---
title: "Audioverarbeitung mittels eines Computers"
author: "Amsakan Bavan"
output: pdf_document
header-includes:
    - \renewcommand{\contentsname}{Inhaltsverzeichnis}
---

\tableofcontents

# 1 Einführung

In der heutigen Zeit, ermöglichen Programme wie Konferenzsoftware, Digitale Audio Workstations, Aufnahmeprogramme, Messagingprogramme und viele mehr, die Möglichkeit Töne, Sprache und Geräusche zu verarbeiten. Dies ist möglich dank digitaler Signalverarbeitung kombiniert mit Echtzeitlösungen, wie Ringpuffern, Pufferung und vielem mehr. In diesem Dokument beleuchten wir einige bestehende Lösungen, welche die Audioverarbeitung auf Computern ermöglichen. Außerdem betrachten wir die Theorie der digitalen Signalverarbeitung und schauen uns auch die Implementierungen von diesen theoretischen Konzepten an. Darüber hinaus implementieren wir ein einfaches Audioverarbeitungsprogramm, welches eine Audiodatei annimmt und eine Filtrierung durch Fourier-Analyse vornimmt. Unter der Audioverarbeitung definieren wir die Komprimierung, Bearbeitung und Übertragung eines bestehenden Audiosignals.

# 2 Bestehende Werke

Ich beziehe mich in dieser Arbeit auf folgende Werke:

- Principles of Digital Audio von Ken C. Pohlmann (ISBN: 978-0071348190)
- Digital Audio Signal Processing von Prof. Dr.-Ing. Udo Zölzer (ISBN: 978-1119832676)
- Perceptual coding of digital Audio der IEEE (DOI: 10.1109/5.842996)
- Fundamentals of Music Processing von Prof. Dr. Meinhard Müller (ISBN: 978-3319219448)
- The computer music tutorial von Curtis Roads (ISBN: 978-0262181587)
- Introduction to digital filters von Julius O. Smith III (ISBN: 978-0974560717)

Diese verwende ich um grundlegende Begriffe in dieser Arbeit zu definieren.

# 3 Bestehende Lösungen

Wie schon vorhin erwähnt, verstehen wir unter der Audioverarbeitung die Komprimierung, Bearbeitung und Übertragung eines bestehenden Audiosignals. Dementsprechend gibt es schon einige bestehende Lösungen für diese:

## 3.1 Bestehende Lösungen zur Audiokomprimierung

Die Audiokomprimierung dient dazu, dass ein digitalisiertes Audiosignal in dessen Bandbreite zu komprimieren, um diese zur Übertragung, Abspeicherung oder Weiterverarbeitung schneller und einfacher handzuhaben. Das analoge Audiosignal wird duch Pulsweitenmodulation abgetastet und digitalisiert. Dabei haben die Abtastparameter, wie Abtastrate und Bittiefe eine große Auswirkung auf der Bandbreite des digitalisierten Signals. Die Standardwerte für ein Musikstück beispielsweise sind eine Abtastrate von 44.100 kHz, eine Bittiefe von 24Bit. Hierbei bewegt man sich in der Größenbereichen von 20 Megabyte bis 60 Megabyte. Diese Größen sind nicht leicht handhabbar für die Übertragung oder gar für die Abspeicherung auf mobilen Endgeräten beispielsweise. Und um diese Handhabung zu realisieren, verwendet man die Komprimierung. Umgesetzt wird das ganze durch sogenannte Codecs, was die Kurzschreibweise für "Coder Decoder" ist. Die Funktionsweise ist hierbei wiefolgt:

Das digitalisierte Audiosignal wird durch einen Kodierer gemäß eines Formates codiert und somit auch komprimiert. Diese codierten und komprimierten Audiodaten kann man übertragen oder auch absperichern und durch die Dekodierung dieses komprimierten Signals, erhält man je nach Codec entweder das Signal wieder in voller Gänze oder eine Annäherung davon (also ein Signal mit Verlust) wieder. Es muss also unterschieden werden zwischen verlustfreien und verlustbehafteten Codes.

Beispiele für verlustfreie Codes sind Free Lossless Audio Codes (kurz: FLAC), Wavpack, ALAC, Monkey Audio, True Audio und weitere. [1]
Beispiele für verlustbehaftete Codes hingegen sind MPEG, Vorbis oder auch Windows Media Audio.

Diese Lösungen werden je nach Anwendungsfall in heutiger Software, welche Audio benötigen weitesgehend verwendet.

## 3.2 Bestehende Lösungen zur Audiobearbeitung

Die Audiobearbeitung dient dazu, dass Bearbeitungen an einem Audiosignal vorgenommen werden können. Einige Beispiele für solche Bearbeitungen sind Verzerrung, das Filtrieren von Frequenzbereichen (oder auch Frequenzbändern), das Anwenden eines Halleffektes oder auch das Verstellen von Tonhöhen bei der Audioaufnahme eines Musikstückes. Für solche Bearbeitungen werden sogenannte Digitale Audio Workstations verwendet. Dies sind Programme, welche dazu dienen anhand digitaler Werkzeuge, Audiosignale zu bearbeiten.

Beispiele für solche Digitalen Workstations sind: Live (Ableton), Pro Tools (Avid), Cubase (Steinberg) oder auch FL Studio (Image Line).

Dabei bauen all diese Werkzeuge und auch die digitalen Workstations auf digitaler Signalverarbeitung mit theoretischen Konzepten wie zum Beispiel der Fourier-Analyse zur Filtrierung oder auch der Faltung zum Imitieren eines Raumhalles.

# 4 Theorie
## 4.1 Digitale Signalverarbeitung
### 4.1.1 Fourier Analyse
### 4.1.2 Faltung

# 5 Implmentierung der Fourier Analyse

# 6 Eigenimplementierung eines Audioverarbeitungsprogramms

# 7 Fazit

# 8 Quellen

[1] https://www.researchgate.net/profile/Teddy-Gunawan/publication/317829002_Investigation_of_Lossless_Audio_Compression_using_IEEE_18572_Advanced_Audio_Coding/links/5a437fcc0f7e9ba868a5847b/Investigation-of-Lossless-Audio-Compression-using-IEEE-18572-Advanced-Audio-Coding.pdf?origin=journalDetail&_tp=eyJwYWdlIjoiam91cm5hbERldGFpbCJ9&__cf_chl_rt_tk=au_e8wiay.b0il5VfKb7.FHV9Kvgkf8SSDz7cRlX7bI-1749802307-1.0.1.1-GD68ZsTC27Jor4BaxrEtT4ifchG27xRHCau3RgFHBrU; Abrufzeitpunkt: 13.06.2025 10:12 Uhr
